### ISSUE TITLE
Request for incubation: rattler

### ISSUE THREAD

**Issue by baszalmstra** [conda/governance#145]
Project URL: https://github.com/mamba-org/rattler
Members of the `rattler` team: @baszalmstra @wolfv @tdejager @ruben-arts @nichmor

We would like to start to migration of [`rattler`](https://github.com/mamba-org/rattler) from `mamba-org` to the `conda` organization as a federated project. We start the journey by requesting incubation through this issue!

**Comment by jezdez** [comment]
Awesome news, everyone! Let’s start collecting questions you may have here for transparency. I’ll follow up with more details and set up the team on a bit.

**Comment by jezdez** [comment]
For the record, per governance policy, [there is no need for a vote to move a project to the incubator](https://github.com/conda/governance/blob/de674bb5410e12083386aab54941d6c69c8518cd/README.md#add-projectrepo-to-incubator) as described in [the section about incubation](https://github.com/conda/governance/blob/de674bb5410e12083386aab54941d6c69c8518cd/README.md#incubation), since "a single member of the Steering Council may add a project to the incubator". I'm just participating in this to help out with the process.

**Comment by jezdez** [comment]
@baszalmstra I've invited everyone listed above to [a new team in the conda-incubator GitHub organization](https://github.com/orgs/conda-incubator/teams/rattler/members). @nichmor @ruben-arts @tdejager Please check your email for the GitHub invitation.

The equivalent team in the main conda organization would be created when the new rattler team would request to [graduate the project to the main conda organization](https://github.com/conda/governance/blob/de674bb5410e12083386aab54941d6c69c8518cd/README.md#incorporate-a-software-project-into-the-main-conda-organization).

**Comment by jezdez** [comment]
@baszalmstra Hey there, how can I help to move this along?

**Comment by baszalmstra** [comment]
Nothing, I just transferred ownership: https://github.com/conda-incubator/rattler 🥳

**Comment by jezdez** [comment]
w00t! I've updated the permissions for the repo to admin for the rattler team in the conda-incubator.
